#!/usr/bin/env bun
/**
 * Generates src/update/build-version.ts from environment variables.
 * Called as part of build:single to embed the git SHA and update URL
 * into the compiled binary.
 *
 * Environment variables:
 *   BUILD_SHA         - Git commit SHA (defaults to "dev")
 *   BUILD_UPDATE_URL  - URL for version.json (defaults to "")
 */

const sha = process.env.BUILD_SHA ?? "dev";
const url = process.env.BUILD_UPDATE_URL ?? "";

const content = `// Auto-generated by scripts/gen-build-version.ts. Do not edit manually.
export const BUILD_SHA = "${sha}";
export const BUILD_UPDATE_URL = "${url}";
`;

await Bun.write("src/update/build-version.ts", content);
